IR-123 DB versioning solution. Debugging the failing step.

diff --git a/.github/workflows/versioning.yml b/.github/workflows/versioning.yml
--- a/.github/workflows/versioning.yml
+++ b/.github/workflows/versioning.yml
@@ -65,7 +65,7 @@ jobs:
           MIN_CHANGESET_DIGITS: 4
         run: |
           set -euxo pipefail
-          
+
           gen_version() {
             local rawVersion=$1
             local minDigits=$2
@@ -76,20 +76,22 @@ jobs:
           major=$(gen_version $(echo $new_version | cut -d. -f1) $MIN_MAJOR_VERSION_DIGITS)
           minor=$(gen_version $(echo $new_version | cut -d. -f2) $MIN_MINOR_VERSION_DIGITS)
           patch=$(gen_version $(echo $new_version | cut -d. -f3) $MIN_PATCH_VERSION_DIGITS)
-          changeset=$(gen_version 0 $MIN_CHANGESET_DIGITS)  # Assuming changeset starts from 0
+          changeset=$(gen_version 0 $MIN_CHANGESET_DIGITS)
 
           newDBRevisionNumber="${major}${minor}${patch}${changeset}"
 
-          # Determine the last existing version for rollback
-          lastExistingVersion=$(find database/ -name "*.update.sql" | sort -V | tail -n 1 | grep -oP '\d{10}')
-
-          if [[ -z "$lastExistingVersion" ]]; then
-            # If it's the first DB version, set the last existing version to 0
-            lastExistingVersion=0
+          # Check for the presence of both update.sql and rollback.sql
+          if [[ -f "database/update.sql" && ! -f "database/rollback.sql" ]] || [[ ! -f "database/update.sql" && -f "database/rollback.sql" ]]; then
+            echo "Error: Only one of update.sql or rollback.sql found. Both files must be present."
+            exit 1
           fi
 
+          # If update.sql exists
           if [[ -f "database/update.sql" ]]; then
+            lastExistingVersion=$(find database/ -name "*.update.sql" | sort -V | tail -n 1 | grep -oP '\d{10}' || echo "0")
+
             echo -e "\nINSERT INTO db_version (revision, direction) VALUES (${newDBRevisionNumber}, 'update');" >> database/update.sql
+
             if [[ "${{ env.BUMP }}" == "major" ]]; then
               mkdir -p database/$major.0.x/
               mv database/update.sql database/$major.0.x/${newDBRevisionNumber}.update.sql
@@ -102,8 +104,10 @@ jobs:
             fi
           fi
 
+          # If rollback.sql exists
           if [[ -f "database/rollback.sql" ]]; then
             echo -e "\nINSERT INTO db_version (revision, direction) VALUES (${lastExistingVersion}, 'rollback');" >> database/rollback.sql
+
             if [[ "${{ env.BUMP }}" == "major" ]]; then
               mkdir -p database/$major.0.x/
               mv database/rollback.sql database/$major.0.x/${newDBRevisionNumber}.rollback.sql
@@ -115,6 +119,7 @@ jobs:
               mv database/rollback.sql database/$major.$minor.x/${newDBRevisionNumber}.rollback.sql
             fi
           fi
+      
 
       - name: Set up Git with PAT, Commit, Tag and push
         run: |
